### PR TITLE
adding my instance

### PR DESCRIPTION
**Pull request by DigitalKaiser**

### CODE REVIEW

**Comment by RiversideRocks** [comment]
Does your instance support SSL?

**Comment by DigitalKaiser** [comment]
Not yet, but I may do it if it is required

**Comment by Perflyst** [comment]
Yes, please add SSL @DigitalKaiser, it's free

**Comment by DigitalKaiser** [comment]
> Yes, please add SSL @DigitalKaiser, it's free

SSL is now enabled and http://invidious.reallyancient.tech/ redirects to https://invidious.reallyancient.tech/

**Pull request merged**
