### PR TITLE
applications.md - Various changes and re-order by oldest to newest (for now)

### PR DESCRIPTION
**Pull request by maboroshin**
No apps will be added or reduced. The explanations are also intact.

----
Changes:

**Applications**

* PlasmaTube is developing quickly, so go up. Multi-language is also available.
* Playlet for Roku is for a relatively minor OS, so go down
* Yattee and WatchTube have also in the App Store.

**Browser Extensions**

* Unifies URL usage patterns for Alter, Inviduration
* Add add-on link for Redirector
* Subgrouping tools for redirects

### CODE REVIEW

**Comment by unixfox** [comment]
ping review @TheFrenchGhosty

**Comment by maboroshin** [comment]
PlasmaTube can now log in to Invidious for installations on FlatHub.

**Review by TheFrenchGhosty — CHANGES_REQUESTED** [review]
Please do not change the order, the order is purposefully like this because it is listed from the oldest to the newest addition. I have plan to have something saying that some of them are "endorsed by us", but for now, this remains this way.

Related: https://github.com/iv-org/documentation/pull/366#pullrequestreview-1435584831

**Comment by maboroshin** [comment]
@TheFrenchGhosty

> the order is purposefully like this because it is listed from the oldest to the newest addition. 

That order is already broken.

**In the list of apps**, the apps have been added to the end of the list in previous README.MD. ([See README.MD](https://github.com/iv-org/invidious/commits/master/README.md)) However, new order of the apps was added to this extensions list by syeopite on Nov 24, 2023. (https://github.com/iv-org/documentation/commit/cbc1df9c5e51348cbaa9b25b38168e4c3878ecbc) 
* HoloPlay is changing from an Android version to an online version in 2023.

**In the list of extensions**, there was a major re-ordering on Oct 18, 2020. And, some cases were added in the middle of the list, not at the end.
* Alter, Nov 27, 2021 : This was placed next to Privacy Redirect. In other words, it is probably because this Alter is the same kind of redirect tool as Privacy Redirect. https://github.com/iv-org/documentation/commit/d4eb1ff27982ddb5f3cb048083fb70f5a20b4eee
* In Oct 18, 2020, the sections "Userscripts" and "Utilities" have been added. https://github.com/iv-org/documentation/commit/03c2af3c219109c03a0f17a1da81ef14f0f676e3
* * [Before](https://github.com/iv-org/documentation/blob/db084fb045cadab7b0005cbb3096350b63906e76/Extensions.md):Alternate Tube Redirector, View on Invidious, Invidition, Privacy Redirect, Invidious Copy URL, SponsorBlock:
* * [After](https://github.com/iv-org/documentation/blob/03c2af3c219109c03a0f17a1da81ef14f0f676e3/Extensions.md) : Privacy Redirect, SponsorBlock, Invidition, Alternate Tube Redirector, Invidious Copy URL, View on Invidious
* * Before:iPhone Redirector Shortcut, FreshRSS Extension
* * After : NitterizeMe (now, UntrackMe), iPhone Redirector Shortcut, FreshRSS Extension
* Privacy Redirect added to middle, Oct 18, 2020: https://github.com/iv-org/documentation/commit/543a225d5b15c21720e058c2aa948fb71be7c491

**Comment by maboroshin** [comment]
For extensions:
Extensions for redirects are all outdated. All will not work properly maybe. So, adding [Predirect](https://github.com/libreom/predirect) extension seems like a good. (Because LibRedirect not listed due to objections by TheFrenchGhosty. https://github.com/iv-org/documentation/issues/229#issuecomment-1295882087 and https://github.com/iv-org/invidious/pull/3901)

If Predirect is added to the end of the list, it opens the 5 outdated extensions first. Some will mistakenly believe that this list is outdated. In this case, it's better to add the 1st.

For user scripts:
For the same reason, Privacy Redirector in user scripts should be at the top, because active development. Invidious Redirect to be 2nd, it's final update in 2021. The others are before 2019. (I'll leave this as a note for not listed app: It's last updated January 2023: [Open source alternative redirector](https://greasyfork.org/ja/scripts/437291-open-source-alternative-redirector))

**Comment by TheFrenchGhosty** [comment]
@maboroshin The order will be modified at a later date. This PR just shouldn't do it.

**Comment by maboroshin** [comment]
@TheFrenchGhosty : If you want to restore the exact order in which they were added, I will do it.

But the added order is not kept as you originally thought. It just replaces one wrong order with another wrong order. There is no point in modifying it.

If rules are needed, you can write "please add to the end" in the comment tag. But adding it at the end would create the misconception that it's an outdated list. Then I will leave it to someone to change the order.

**Comment by TheFrenchGhosty** [comment]
@maboroshin 

> If you want to restore the exact order in which they were added, I will do it.

Go ahead yes sure.

I wasn't aware that so much was changed over the years and thought it was still the "default" order from 4-5 years ago.

Right now we should do the minimum, I plan to reorder the list with our official recommendations at a later date

**Comment by maboroshin** [comment]
@TheFrenchGhosty : I done. The last item listed was always re-added to the end of the list.

**Review by TheFrenchGhosty — APPROVED** [review]

**Pull request merged**
