### PR TITLE
Bring back invidious.048596.xyz

### PR DESCRIPTION
**Pull request by austinhuang0131**
I use it. I am aware that it goes off intermittently (Once or twice a day, ~5 minutes each) but it is mostly online.

cc @tenpura-shrimp . Also, (I think you own the instance?) you need to update it to fix the channel page problem.

### CODE REVIEW

**Comment by tenpura-shrimp** [comment]
updated.

**Comment by austinhuang0131** [comment]
@tenpura-shrimp your ssl expired

**Comment by tenpura-shrimp** [comment]
who the heck enabled hsts

**Comment by austinhuang0131** [comment]
@tenpura-shrimp your ssl expired again

**Comment by tenpura-shrimp** [comment]
HSTS HATE

HSTS AWAY

**Pull request merged**
