### PR TITLE
Update invidious-instances.md (New instance added)

### PR DESCRIPTION
**Pull request by dejalavidavolar**
New instance added: https://notyoutube.org. (line 58 and 59)

### CODE REVIEW

**Comment by dejalavidavolar** [comment]
Solved #56

**Comment by Testsr** [comment]
Closes #56.

**Comment by RiversideRocks** [comment]
Looks good, I think you might want to note you are running modified source code.

**Comment by TheFrenchGhosty** [comment]
@RiversideRocks It's not a modified source code.

**Comment by RiversideRocks** [comment]
Oh I've never seen this alternate home screen, sorry about that!

**Comment by syeopite** [comment]
Looks good to me. Merged!

**Pull request merged**
