### PR TITLE
Add yt2alt

### PR DESCRIPTION
**Pull request by iBicha**

### CODE REVIEW

**Comment by TheFrenchGhosty** [comment]
Waiting on https://github.com/iv-org/documentation/pull/481

**Comment by iBicha** [comment]
@TheFrenchGhosty thanks, I just noticed there's a category called `Utilities`. Let me know if that makes more sense than `Applications`

**Comment by TheFrenchGhosty** [comment]
@iBicha Utilities was a category made for stuff related to Invidious itself... though I guess this is also an utility but for users... so applications should be the best (unless we split utilities between things made for admin and things made for users, which seems unnecessary since there's only one of each)

**Comment by TheFrenchGhosty** [comment]
@iBicha Can you please fix the merge conflict, I'll merge this PR when this is done

**Comment by TheFrenchGhosty** [comment]
Well, I had some time to do it myself

**Comment by iBicha** [comment]
> Well, I had some time to do it myself

Thanks!

**Pull request merged**
