### PR TITLE
Add inv.cthd.icu (Closes #156)

### LINKED ISSUE #156: [New instance] inv.cthd.icu
### URL

https://inv.cthd.icu

### Mandatory checks

- [x] Instance has a domain name
- [X] Instance is served over HTTPS
- [X] Statistics (`/api/v1/stats`) are enabled

### Maintainer chart

- [X] Ensure that my instance is up to date (less than one month old)
- [X] Ensure a proper uptime of my instance (around 90%)

### Host country

Serbia

### Man in the Middle

_No response_

### Source code URL

https://github.com/cysea/invidious-custom

### Analytics

- [ ] They are GDPR/CCPA compliant
- [ ] This is stated in your Privacy Policy
- [x] You have provided the source code's URL in the dedicated field above

### Additionnal informations

Just a vanilla instance for my friends, myself and whoever wants to join in.

At some point I'll be making modifications similar to the [yewtu.be instance](https://github.com/unixfox/invidious-custom), but will provide updates here once that is done.

### PR DESCRIPTION
**Pull request by TheFrenchGhosty**
It's hasn't been a month, but the instance is properly updated and respects all the requirements, so we can add it now.

Please @cysea confirm that the instance is ready to be added to the instances list.

Note: One issue I can see is that your fork is based on @unixfox work, that isn't released under an open source license. So he might not necessarily be okay with that.

### CODE REVIEW

**Comment by unixfox** [comment]
I don't mind that someone copy my workflow (patches with docker) and my custom invidious pages, but at least they should modify it so that it doesn't look almost exactly like mine.

I'm sorry, but to my eyes, it looks like an almost copy pasta of my donation page.

inv.cthd.icu:
image

yewtu.be:
image

**Comment by cysea** [comment]
I'm not going to deny it, this was pure copy paste. 0 to 100, but I bet you wouldn't mind if I accidentally left your crypto wallet addresses, would you now? :)

Also, I wish I could actually learn your workflow because I'm literally doing everything manually...

Anyways, made some changes, you can check it out now.

**Review by unixfox — APPROVED** [review]

**Comment by unixfox** [comment]
Thank you for the modifications. I approved the PR, waiting for the approval of the other @iv-org/developers.

**Comment by TheFrenchGhosty** [comment]
Perfect.

> Please @cysea confirm that the instance is ready to be added to the instances list.

**Comment by cysea** [comment]
@TheFrenchGhosty Confirmed, literally watching a video right now.

**Comment by TheFrenchGhosty** [comment]
@cysea alright! Thanks for hosting an instance :)

**Pull request merged**
