### PR TITLE
Add my instance

### PR DESCRIPTION
**Pull request by RiversideRocks**

### CODE REVIEW

**Comment by Testsr** [comment]
Instance  link is https://inv.riverside.rocks.

**Comment by RiversideRocks** [comment]
Any changes I should make so this PR gets merged?

**Comment by syeopite** [comment]
The instance hasn't been updated in almost a month now. You sure you can maintain it? Youtube changes frequently and in turn Invidious does as well. Please make sure the instance is updated frequently. It's a requirement that all instances has to be no more than a month old.

**Comment by RiversideRocks** [comment]
Thanks, created a cronjob to update weekly.

**Comment by RiversideRocks** [comment]
Good point, I'll do more updates from now on.

**Comment by syeopite** [comment]
Awesome! Looks like the instance is updated. I'll go ahead and merge it.

**Pull request merged**
