### PR TITLE
Move to mkdocs-material

### PR DESCRIPTION
**Pull request by TheFrenchGhosty**
The documentation has been moved to mkdocs-materials, meaning that it doesn't requires JS to just read the content.

The old VPS that was still only hosting the documentation will be killed.

The use of mkdocs-materials is temporary, we'll move to something based on rst files later this year.

If you link directly to any page of our documentation: those links will 404.

**Has to be merged at the same time as** https://github.com/iv-org/instances-api/pull/37

### CODE REVIEW

**Comment by unixfox** [comment]
I strongly disagree with the move to rst, it's a barrier to beginners.

**Comment by TheFrenchGhosty** [comment]
@unixfox We literally have been planning that for almost a year. It's literally one of @SamantazFox objective for this year.

**Comment by unixfox** [comment]
Probably because I never heard about it until today :).

**Comment by TheFrenchGhosty** [comment]
@unixfox We'll have to discuss it properly later then.

Let's merge this PR first :)

**Review by unixfox — APPROVED** [review]

**Comment by SamantazFox** [comment]
Small question: why did you add all the assets and other final files?

**Comment by TheFrenchGhosty** [comment]
@SamantazFox I wanted to do it quickly, I plan to setup CI to a Docker image

**Pull request merged**
