### PR TITLE
Re-license under the VIRAL PUBLIC LICENSE (VPL)

### PR DESCRIPTION
**Pull request by TheFrenchGhosty**
Like CC0 but better in every way.

https://viralpubliclicense.org/

This effectively mean that we won't ever be able to change this license (which is the point).

Other more restrictive alternatives are CC-BY-SA / CC-BY-NC-SA / CC-BY-ND

### CODE REVIEW

**Comment by SamantazFox** [comment]
I'm not sure why we would need to change. CC0 is already public domain.

**Comment by TheFrenchGhosty** [comment]
@SamantazFox CC0 is too permissive in my opinion. It allows 100% commercial/proprietary use.

**Comment by unixfox** [comment]
imo pretty useless to change the license. the current one is enough and very popular/well known.

**Comment by TheFrenchGhosty** [comment]
@unixfox As I said: "CC0 is too permissive in my opinion. It allows 100% re-licensing to a proprietary license. This blocks all re-licensing."

We shouldn't allow proprietary re-licensing.

**Comment by TheFrenchGhosty** [comment]
@unixfox @SamantazFox 

Do I merge this PR? Please reply with yes or no.

If no tell me if you prefer another license, or if you prefer to stay on CC0.

Again: "CC0 is too permissive in my opinion. It allows 100% re-licensing to a proprietary license. This blocks all re-licensing. We shouldn't allow proprietary re-licensing."

**Comment by unixfox** [comment]
no because https://github.com/iv-org/documentation/pull/246#issuecomment-1144149812

**Comment by TheFrenchGhosty** [comment]
License won't be changed.

**Pull request closed without merging**
