### PR TITLE
Remove invidious.exonip.de because it is broken

### PR DESCRIPTION
**Pull request by unixfox**
4 issues about the instance were opened in the last few days:
- https://github.com/iv-org/invidious/issues/2163
- https://github.com/iv-org/invidious/issues/2162
- https://github.com/iv-org/invidious/issues/2161
- https://github.com/iv-org/invidious/issues/2160

I think we should remove it for the moment until the errors are fixed. For example, I just tested, and I can't register on the instance.

@Exonip Could fix the issues on your instance?

### CODE REVIEW

**Comment by syeopite** [comment]
There's also an AGPL violation. If you'd like to add back your instance either use the Invidious source code without modification or disclose your source and clearly state it is modified like what ytprivate does.

**Comment by Exonip** [comment]
Hey, the instances source code is not changed as only the file default.css is rewritten by nginx. The instance is also offline because the user database for some reason got to a size of 600 gb and I’m currently working on fixing that.

**Comment by unixfox** [comment]
Great, keep us updated once you have fixed the issues. About the big size of the database, you should look into this guide: https://docs.invidious.io/Database-Information-and-Maintenance.md

**Comment by syeopite** [comment]
#2042 could also be related

**Comment by Exonip** [comment]
Thanks for linking me to that but the problem seems to be another one as the video tables takes up about 7 gb of storage and the user table 600gb. It would be easier to recreate the database but I don’t want users to loose there data. Also does it count as a violation of the file is rewritten? And how should it be disclosed as the source of the css file is publicly acessable already?

**Comment by unixfox** [comment]
> Thanks for linking me to that but the problem seems to be another one as the video tables takes up about 7 gb of storage and the user table 600gb. It would be easier to recreate the database but I don’t want users to loose there data.

Execute this PostgreSQL command and this will fix the issue: `VACUUM FULL users;`
It may take a while to complete, but that's normal.

**Comment by Exonip** [comment]
The instance has now been temporarily fixed and I’ll restore a backup of the user table later today. I still don’t know what to do about the default.css file as the invidious source is not changed.

**Comment by SamantazFox** [comment]
> The instance has now been temporarily fixed and I’ll restore a backup of the user table later today. I still don’t know what to do about the default.css file as the invidious source is not changed.

If you have any nginx configs that rewrite the CSS, you should remove them.

**Comment by Exonip** [comment]
Is it also possible to upload the nginx configuration and css file to a public repository and add this to the instance list?

**Comment by unixfox** [comment]
> Is it also possible to upload the nginx configuration and css file to a public repository and add this to the instance list?

Yes that's what ytprivate do.

**Comment by Exonip** [comment]
I created a pull request for it #89

**Pull request merged**
