### PR TITLE
Add instances to instances list

### PR DESCRIPTION
**Pull request by Eggo-Plant**

### CODE REVIEW

**Comment by Eggo-Plant** [comment]
As you can see, I'm not very good at getting it perfect on the first commit.

**Comment by hackerncoder** [comment]
There's a thing called [squash](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#_squashing) if you make too many commits.

**Comment by Eggo-Plant** [comment]
That's really helpful. I'm fairly new to git, so I don't know too much about it.

**Comment by syeopite** [comment]
Don't worry I can squash it when merging! Anyways could you add something to the onion link that associates it with it's clearnet counterpart?

**Comment by Eggo-Plant** [comment]
As in change the URL of the hidden service? Or add something after both the onion link and clearnet link that lets you know they're on the same server?

**Comment by syeopite** [comment]
The latter something like a simple `(https://i.eggo.xyz)` after the onion link section would be fine, no need to change the URLs!

**Comment by syeopite** [comment]
Yep that looks good. I just need you to update your instance before I can merge it. Youtube changes frequently and in turn Invidious does as well, which is why if an instance is more than a month behind we'll be forced to remove it. So please remember to update your instance constantly!

**Comment by Eggo-Plant** [comment]
How should I go about updating it. The Invidious updater script is telling me that it's already up-to-date and I'm not sure why.

**Comment by syeopite** [comment]
Huh that's strange. I'll suggest opening an issue on its repo to see if the maintainer can help you resolve that. For now you should update it manually with `git pull` and rebuild.

**Comment by Eggo-Plant** [comment]
Strange... `git pull` is also telling me that the repo is up to date. I've confirmed that the remote is also the correct repo:
```
origin	https://github.com/iv-org/invidious (fetch)
origin	https://github.com/iv-org/invidious (push)
```
It must be some problem with git then, the script probably uses git.

**Comment by syeopite** [comment]
Try `git fetch && git reset --hard origin/master`

**Comment by Eggo-Plant** [comment]
I think that did the trick, `git show --oneline -s` shows me that I'm on commit "`75e5b49`". I've restarted the Invidious service, but it still shows I'm on the older version.

**Comment by syeopite** [comment]
That's the culprit then. Go ahead and rebuild Invidious with `crystal build src/invidious.cr --release` and then restart the Invidious service.

**Comment by Eggo-Plant** [comment]
Alright, I'm doing that. It's probably gonna take a while since it's on my super cheap VPS.

**Comment by Eggo-Plant** [comment]
Sorry for the delay, I was having some issues starting invidious. I migrated to a docker container and things seems to be working fine now.

**Comment by hackerncoder** [comment]
Hey @Eggo-Plant! Seems you had a merge conflict. When that happens git will add lines with <<<<<<<, =======  and >>>>>>>.

Basically it says this (<<<<<<< HEAD) is the difference in our current file and (=======) this is the difference in the upstream file (>>>>>>> 577ed99e5bc184364b0bc3fe556b0b8dfacb1fcb).

You should delete and move the lines in between (the <s, =s and >s) so that it fits how it should look.

E.g:
```
<<<<<<< HEAD
* [i.eggo.xyz](https://i.eggo.xyz) 🇺🇸
=======
* [invidious.blamefran.net](https://invidious.blamefran.net) 🇺🇸
>>>>>>> 577ed99e5bc184364b0bc3fe556b0b8dfacb1fcb
```

Becomes
```
* [invidious.blamefran.net](https://invidious.blamefran.net) 🇺🇸
* [i.eggo.xyz](https://i.eggo.xyz) 🇺🇸
```

**Pull request merged**
