### PR TITLE
Update Invidious-Instances.md

### PR DESCRIPTION
**Pull request by Aidan16**
invidious.blamefran.net added

### CODE REVIEW

**Comment by syeopite** [comment]
Looks like the instance is behind Cloudflare. Please mark it as such!

**Comment by unixfox** [comment]
> Looks like the instance is behind Cloudflare. Please mark it as such! The instance should also be appended to the end of the list, not the start.

It's not under cloudflare anymore it seems.

**Comment by syeopite** [comment]
Not sure if this counts as under cloudflare but the instance is using their nameservers
Screenshot_20210517-093113

**Comment by unixfox** [comment]
> Not sure if this counts as under cloudflare but the instance is using their nameservers
> Screenshot_20210517-093113

And? That's not an issue... what's an issue is that if the HTTP traffic is being proxied through Cloudflare servers but that's not the case here.

**Comment by Aidan16** [comment]
I plan to keep it not behind CloudFlare, sorry for the late response. :)

**Pull request merged**
