### PR TITLE
Add instance youtube.076.ne.jp

### LINKED ISSUE #119: New Instance
Please add → https://youtube.076.ne.jp
Sarver rocation: japan

### PR DESCRIPTION
**Pull request by SamantazFox**
Closes #119

- [x] Instance has a domain name and is served via HTTPS
- [x] Instance has been updated in the last month
- [x] Statistics (`/api/v1/stats`) are enabled
- [x] The instance doesn't have any trackers/ads
- [x] If the instance is using any anti-DDoS/bot Protection/MITM, this has been mentioned
- [x] If the instance is running a modified source code, a link has been provided

Nb: From what I found, it doesn't seem to use anything like CF. @TechnicalSuwako can you please confirm?

### CODE REVIEW

**Comment by TechnicalSuwako** [comment]
@SamantazFox What is CF?（；^ω^）

**Comment by SamantazFox** [comment]
> @SamantazFox What is CF?（；^ω^）

CloudFlare :)

**Comment by TechnicalSuwako** [comment]
@SamantazFox I'm not using it.

**Comment by TheFrenchGhosty** [comment]
@TechnicalSuwako The AGPL requires you to state your changes, please do so in the fork README.md (or somewhere in the instance).

Please link to your modified source code somewhere in the page (footer ideally) without removing the link to the invidious source code : `a) The work must carry prominent notices stating that you modified it, and giving a relevant date.` (from https://www.gnu.org/licenses/agpl-3.0.en.html )

Other than that, everything is good.

**Comment by TechnicalSuwako** [comment]
@TheFrenchGhosty https://git.076.ne.jp/TechnicalSuwako/invidious-mod/-/commit/e926519e2be546fce074a9b27991c4cdfd0a121a

https://git.076.ne.jp/TechnicalSuwako/invidious-mod/-/commit/0cd655f459bd5f06e3416a5d1a90e4743329a215

**Comment by SamantazFox** [comment]
Thanks for your cooperation :)

Don't forget to update regularly (at least once a month) to stay in the public list!

**Pull request merged**
