### PR TITLE
Add inv.privacy.com.de

### PR DESCRIPTION
**Pull request by unixfox**
Closes https://github.com/iv-org/documentation/issues/260

### CODE REVIEW

**Comment by Exonip** [comment]
> Blocked by [#260 (comment)](https://github.com/iv-org/documentation/issues/260#issuecomment-1184882198)

Everything is configure as mentioned under "Post-install configuration".

**Comment by TheFrenchGhosty** [comment]
@Exonip No, `domain:` isn't set.

**Comment by Exonip** [comment]
> @Exonip No, `domain:` isn't set.

I have domain: inv.privacy.com.de set in my docker-compose.yml file

**Comment by unixfox** [comment]
> > @Exonip No, `domain:` isn't set.
> 
> I have domain: inv.privacy.com.de set in my docker-compose.yml file

@TheFrenchGhosty good to be added now?

**Comment by TheFrenchGhosty** [comment]
@unixfox The issue is fixed now, something was definitely wrong, either an Invidious config, or something that was rewriting the URL, but it looks like you fixed it.

@Exonip Instance is properly configured and has good uptime.

Are you ready for it to be added to the instance list?

**Pull request merged**
