### PR TITLE
Add a new rule about access restriction

### PR DESCRIPTION
**Pull request by TheFrenchGhosty**
Related to https://github.com/iv-org/documentation/pull/396

I personally want instances owners to be able to block juridical person if they want to, but natural person (i.e Humans) shouldn't be blocked for any reason.

### CODE REVIEW

**Review by unixfox — APPROVED** [review]

**Comment by SamantazFox** [comment]
I'd have also taken the opportunity to change the note right below:
`that repeatedly breaks` => `that is breaking`

**Comment by TheFrenchGhosty** [comment]
@SamantazFox Ah oops, merged too soon.

**Comment by SamantazFox** [comment]
I opened a new PR for that.

**Comment by tuxayo** [comment]
If an instance has in it's TOS "no nazis, no misogynists, no facists, no zionists (as in supporting the apartheid-like situation)" that should be ok. (and it's an arbitrary reason)

The «any [natural person](https://en.wikipedia.org/wiki/Natural_person) ([...], access by a natural person MUST NOT be disallowed for arbirary reason)» is a bit too simplistic in that it doesn't account for the systemic power struggles in the different societies.

That adds much more complexity and I don't think it makes sense for invidious so no worries until a case arrises. But let's keep that in mind if that happens. Or for other contexts when for example non-mixed policies might make sense. Or just rejection of political ideologies that intrinsically and strong violate basic human rights.

**Comment by TheFrenchGhosty** [comment]
@tuxayo 

The «any [natural person](https://en.wikipedia.org/wiki/Natural_person) ([...], access by a natural person MUST NOT be disallowed for arbirary reason)» is a bit too simplistic in that it doesn't account for the systemic power struggles in the different societies.

That's the point.

A human shouldn't be disallowed access for arbitrary reason, including "power struggles in the different societies".

**Pull request merged**
