### PR TITLE
Add README instructions for serving the docs locally

### PR DESCRIPTION
**Pull request by Wint3rmute**
Hey!

While working on #286 I've noticed that there is no described way to locally test the changes made in the documentation. 

The command added to readme comes from the [Docker Hub page of squidfunk/mkdocs-material](https://hub.docker.com/r/squidfunk/mkdocs-material/#!), the image you're using in your `Dockerfile`

### CODE REVIEW

**Comment by Wint3rmute** [comment]
If you'd like me to extend the documentation's readme further, let me know :)

**Comment by TheFrenchGhosty** [comment]
Hello, this builds the documentation, there is a way to run mkdocs in "server" mode which make it run a web server... I can't remember how though.

Also, we should add a way to run it without docker

**Comment by Wint3rmute** [comment]
> this builds the documentation, there is a way to run mkdocs in "server" mode which make it run a web server...

I'm not sure if you're correct here. Running the command provided in the MR runs `mkdocs` in server mode with live reload, which is just what is needed to work on the documentation. I'm providing a screenshot of my terminal as a proof:

image

**Comment by TheFrenchGhosty** [comment]
@Wint3rmute Oh my bad, sorry. I didn't re-check and just assumed it would build.

For the second point, can you please add some steps to set it up without docker? (otherwise I can merge as is)

**Comment by Wint3rmute** [comment]
Sure, added steps to build without docker, using a local installation of `mkdocs-material`

**Comment by TheFrenchGhosty** [comment]
Thank you :)

**Pull request merged**
