### PR TITLE
chore: update applications list

### PR DESCRIPTION
**Pull request by SethFalco**
### Chores

* Converts all lists in this page to tables.
* Fixes various typos found in the document.

---

### Changes to the actual list

* Replaces Roku link for Playlet with one that doesn't require authentication to read.
* Removes Invidition, as the add-on's page literally instructs users to just use Privacy Redirect instead.
* Removes Alternate Tube Redirector, as this has not been maintained in years and was removed from the Mozilla add-on.
* Removes Kodi add-on (by TheAssassin) as this is no longer maintained, repo was archived, and search is broken.
* Renames Another Kodi add-on (by lekma) to just Kodi add-on as this is actively maintained and is far ahead in terms of features compared to the previous one.

---

Preview here:
https://github.com/SethFalco/documentation-1/blob/chore-apps/docs/applications.md

**Ignore LibRedirect in the screenshots, I've removed that in the PR. [[reference]](https://github.com/iv-org/invidious/pull/3901)**

image

image

### CODE REVIEW

**Comment by maboroshin** [comment]
The idea of replacing Privacy Redirect with LibRedirect in README.md is rejected. https://github.com/iv-org/invidious/pull/3901

However, Privacy Redirect has been discontinued since December 2021. So, LibRedirect is a candidate for alternative Privacy Redirect. It would be better to list both. I think so.

**Comment by maboroshin** [comment]
There are an opinion against LibRedirect in #3901.

**Comment by SethFalco** [comment]
> Ignore LibRedirect in the screenshots, I've removed that in the PR. https://github.com/iv-org/invidious/pull/3901

I added this to my original PR, though I appreciate the screenshot may cause confusion.
I saw that feedback, so it's already been excluded from the PR.

**Comment by TheFrenchGhosty** [comment]
Thanks a lot!

**Pull request merged**
