### PR TITLE
Set Postgres to version 10 and add notice

### PR DESCRIPTION
**Pull request by confuzeus**
Issue #3003 showed that using Postgres>10 caused a Invalid memory
access error. Use Postres 10 by default in the compose file and let
the user play around with different versions if he wants.

### CODE REVIEW

**Comment by unixfox** [comment]
Did you try with postgres 13?

**Comment by confuzeus** [comment]
@unixfox I just tried Postgres 14 again and had no issues. I don't know of the problem was fixed in a recent commit or if it's a stability issue that pops up at random times.

Personally, Postgres 10 has been stable for me since you suggested it.

Feel free to close this PR if it's not needed.

**Comment by unixfox** [comment]
I'm closing this PR because @TheFrenchGhosty have plans to put postgres 13 by default in the documentation.

**Comment by TheFrenchGhosty** [comment]
@unixfox I do want to stay on 14 actually, since it works in production, I just want to fix it in development too, and I don't know why.

**Pull request closed without merging**
